stages:
  - build
  - test
  - optional
  - check

variables:
  GNATFORMAT_DATE: 20260721
  # Set to --build-date=YYYYMMDD on a day where there is a QA incident so that
  # the CI works with components from a previous date
  ANOD_BUILD_DATE_ARG: ""

include:
  # Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

  # gnatformat check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/gnatformat@main
    inputs:
      stage: check
      anod-spec: gnattest
      gnatformat-args: -P src/build.gpr --check
      install-gnatformat: true
      install-gnatformat-extra-anod-args: -Qdate=$GNATFORMAT_DATE

  # Build (instrumented)
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: build
      job-name: instrumented-build
      anod-args: run build $ANOD_BUILD_DATE_ARG
      anod-latest: false
      cpus: 16
      image: pe-base
      save-component: true
      save-anod-logs: true

  # Testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["instrumented-build:linux"]
      job-name: gnattest
      anod-args: run test_native $ANOD_BUILD_DATE_ARG
      anod-latest: false
      image: pe-base
      cpus: 16
      disk: 80

  # Testing cross - light runtime, 32bit target
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["instrumented-build:linux"]
      job-name: gnattest-cross-light
      anod-args: run test_cross_light $ANOD_BUILD_DATE_ARG
      anod-latest: false
      image: pe-base
      cpus: 16
      disk: 80

  # Testing cross - embedded runtime, 64bit target
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["instrumented-build:linux"]
      job-name: gnattest-cross-embedded
      anod-args: run test_cross_embedded $ANOD_BUILD_DATE_ARG
      anod-latest: false
      image: pe-base
      cpus: 16
      disk: 80



  # Non instrumented builds of gnattest go into the testing stage, both Linux
  # and Windows.
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: test
      anod-args: build gnattest $ANOD_BUILD_DATE_ARG
      anod-latest: false
      linux: true
      cpus: 8
      disk: 80
      windows: true
      windows-cpus: 2
      windows-mem: 8


  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      needs: ["instrumented-build:linux"]
      job-name: gnattest-gnatfuzz
      anod-args: run test_gnatfuzz_tests $ANOD_BUILD_DATE_ARG
      anod-latest: false
      image: pe-base
      cpus: 8
      disk: 80
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            paths:
              - src/tgen/**/*
              - src/test-*
              - src/utils-*
              - share/tgen/templates/**/*
              - testsuite/testsuite.py
              - testsuite/drivers/gnattest_tgen.py
            compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME


.common_test_before_script: &test_before_script
  before_script:
    - mkdir $CI_PROJECT_DIR/coverage

.common_test_after_script: &test_after_script
  after_script:
    - cat /tmp/ci_env.sh
    - . /tmp/ci_env.sh
    - find $ANOD_DEFAULT_SANDBOX_DIR -name "cobertura.xml" -exec mv {} $CI_PROJECT_DIR/coverage/cobertura.xml \;

.common_artifacts_bits: &artifacts
  artifacts:
    paths:
      - xunit-*.xml
      - coverage/cobertura.xml

    reports:
      junit: xunit-*.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml

gnattest:linux:
  <<: *test_before_script
  <<: *test_after_script
  <<: *artifacts

gnattest-gnatfuzz:linux:
  <<: *test_before_script
  <<: *test_after_script
  <<: *artifacts

gnattest-cross-light:linux:
  <<: *test_before_script
  <<: *test_after_script
  <<: *artifacts

gnattest-cross-embedded:linux:
  <<: *test_before_script
  <<: *test_after_script
  <<: *artifacts
