"""Gnattest utility functions.

This module exposes utility functions, to interact with gnattest and
factorize some common test utils.
"""

import os
from subprocess import PIPE, STDOUT
from sys import stderr
import sys
from e3.os.process import Run
from e3.os.fs import which

from suite.context import thistest


def run_wrapper(
    args: list[str],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **kwargs,
) -> Run:
    """
    Wrapper around e3.os.process.Run which also performs some logging
    By default the output and error of the subprocess are forwarded to
    stderr/stdout to be part of the test baseline, this can be prevented by
    passing False to `output_in_baseline`.
    """
    # In order to forward the subprocess output to the baseline we need to be
    # able to retrieve it, so force the output and error to be piped.
    if output_in_baseline:
        kwargs["output"] = PIPE
        kwargs["error"] = STDOUT

    thistest.log(" ".join(args), True)
    ret = Run(args, **kwargs)
    if output_in_baseline:
        output = ret.out
        error = ret.err
        if os.name == "nt":
            output = output.replace("\r\n", "\n")
            error = error.replace("\r", "")
        print(output, flush=True, end="")
        print(error, file=stderr, flush=True, end="")
    if (not allow_failure and ret.status != 0) or thistest.options.log_all:
        thistest.output_report(ret.out, new_line=False)
        thistest.output_report(ret.err, new_line=False)
        if not allow_failure and ret.status != 0:
            thistest.n_failed += 1
            thistest.result()
    return ret


def run_command(
    command: str,
    gpr: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Run a command with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross generation for example.
    """
    test_args = [command, f"-P{gpr}"]
    options = thistest.options

    if options:
        if options.RTS:
            test_args.append("--RTS=" + options.RTS)
        if options.target:
            test_args.append("--target=" + thistest.env.target.platform)
    test_args.extend(args)
    return run_wrapper(test_args, output_in_baseline, allow_failure, **run_args)


def run_gnattest(
    gpr: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Run gnattest with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross generation for example.
    """
    thistest.log(f"Gnattest command:{os.linesep}\t", False)
    return run_command(
        "gnattest", gpr, args, output_in_baseline, allow_failure, **run_args
    )


def build_harness(
    gpr: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Build the harness generated by gnattest with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross compilation for example.
    """
    thistest.log(f"Harness build command:{os.linesep}\t", False)
    return run_command(
        "gprbuild", gpr, args, output_in_baseline, allow_failure, **run_args
    )

def run_harness(
    executable: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Run the built harness with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross execution for example.
    """
    options = thistest.options
    harness_args = []
    if options:
        if options.target:
            harness_args.extend(
                [
                    sys.executable,
                    which("run-cross2"),
                    "--save-temps",
                ]
            )
            harness_args.append(f"--target={options.target}")

    harness_args.append(executable)
    harness_args.extend(args)

    thistest.log(f"Harness run command:{os.linesep}\t", False)
    return run_wrapper(harness_args, output_in_baseline, allow_failure, **run_args)
