"""Gnattest utility functions.

This module exposes utility functions, to interact with gnattest and
factorize some common test utils.
"""

import os
from shutil import which
from sys import stderr, stdout
import sys
from e3.os.process import Run

from suite.context import thistest


def run_wrapper(
    args: list[str],
    allow_failure: bool = False,
    **kwargs,
):
    # Check if ouptut and error are already present,
    # if not default to catching stdout and stderr.
    if "output" not in kwargs:
        kwargs["output"] = stdout

    if "error" not in kwargs:
        kwargs["error"] = stderr

    thistest.log(" ".join(args), True)
    ret = Run(args, **kwargs)
    if not allow_failure:
        if ret.status != 0:
            thistest.output_report(ret.out)
            thistest.output_report(ret.err)
            thistest.n_failed += 1
            thistest.result()
    return ret


def run_command(
    command: str,
    gpr: str,
    args: list[str] = [],
    allow_failure: bool = False,
    **run_args,
):
    """
    Run a command with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross generation for example.
    """
    test_args = [command, f"-P{gpr}"]
    options = thistest.options

    if options:
        if options.RTS:
            test_args.append("--RTS=" + options.RTS)
        if options.target:
            test_args.append("--target=" + thistest.env.target.platform)
    test_args.extend(args)
    return run_wrapper(test_args, allow_failure, **run_args)


def run_gnattest(
    gpr: str, args: list[str] = [], allow_failure: bool = False, **run_args
):
    """
    Run gnattest with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross generation for example.
    """
    thistest.log(f"Gnattest command:{os.linesep}\t", False)
    return run_command("gnattest", gpr, args, allow_failure, **run_args)


def build_harness(
    gpr: str, args: list[str] = [], allow_failure: bool = False, **run_args
):
    """
    Build the harness generated by gnattest with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross compilation for example.
    """
    thistest.log(f"Harness build command:{os.linesep}\t", False)
    return run_command("gprbuild", gpr, args, allow_failure, **run_args)


def run_harness(
    executable: str, args: list[str] = [], allow_failure: bool = False, **run_args
):
    """
    Run the built harness with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross execution for example.
    """
    options = thistest.options
    harness_args = []
    if options:
        if options.target:
            harness_args.extend(
                [
                    sys.executable,
                    which("run-cross2"),
                    "--save-temps",
                ]
            )
            harness_args.append(f"--target={options.target}")

    harness_args.append(executable)
    harness_args.extend(args)

    thistest.log(f"Harness run command:{os.linesep}\t", False)
    return run_wrapper(harness_args, allow_failure, **run_args)
