"""Gnattest utility functions.

This module exposes utility functions, to interact with gnattest and
factorize some common test utils.
"""

from glob import glob
import os
from subprocess import PIPE, STDOUT
from sys import stderr
import sys

from e3.os.process import Run
from e3.os.fs import which

from suite.context import thistest


def run_wrapper(
    args: list[str],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **kwargs,
) -> Run:
    """
    Wrapper around e3.os.process.Run which also performs some logging
    By default the output and error of the subprocess are forwarded to
    stderr/stdout to be part of the test baseline, this can be prevented by
    passing False to `output_in_baseline`.
    """
    # In order to forward the subprocess output to the baseline we need to be
    # able to retrieve it, so force the output and error to be piped.
    if output_in_baseline:
        kwargs["output"] = PIPE
        kwargs["error"] = STDOUT

    thistest.log(" ".join(args), True)
    ret = Run(args, **kwargs)
    if output_in_baseline:
        output = ret.out
        error = ret.err
        if os.name == "nt":
            output = output.replace("\r\n", "\n")
            error = error.replace("\r", "")
        print(output, flush=True, end="")
        print(error, file=stderr, flush=True, end="")
    if (not allow_failure and ret.status != 0) or thistest.options.log_all:
        thistest.output_report(ret.out, new_line=False)
        thistest.output_report(ret.err, new_line=False)
        if not allow_failure and ret.status != 0:
            thistest.n_failed += 1
            thistest.result()
    return ret


def run_command(
    command: str,
    gpr: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Run a command with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross generation for example.
    """
    test_args = [command, f"-P{gpr}"]
    options = thistest.options

    if options:
        if options.RTS:
            test_args.append("--RTS=" + options.RTS)
        if options.target:
            test_args.append("--target=" + thistest.env.target.platform)
    test_args.extend(args)
    return run_wrapper(test_args, output_in_baseline, allow_failure, **run_args)


def run_gnattest(
    gpr: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Run gnattest with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross generation for example.

    If the GNATTEST_DEBUG env variable is set, -d1 and -dn are added to the
    command line in order to aid debugging (preserve temp dir, compile TGen
    harness with debug info)
    """
    thistest.log(f"Gnattest command:{os.linesep}\t", False)
    return run_command(
        "gnattest",
        gpr,
        args + (["-d1", "-dn"] if os.environ.get("GNATTEST_DEBUG", None) else []),
        output_in_baseline,
        allow_failure,
        **run_args,
    )


def build_harness(
    gpr: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Build the harness generated by gnattest with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross compilation for example.
    """
    thistest.log(f"Harness build command:{os.linesep}\t", False)
    return run_command(
        "gprbuild", gpr, args, output_in_baseline, allow_failure, **run_args
    )


def run_harness(
    executable: str,
    args: list[str] = [],
    output_in_baseline: bool = True,
    allow_failure: bool = False,
    **run_args,
) -> Run:
    """
    Run the built harness with the specified arguments.

    Add additional arguments that must be present regardless of the
    current test, to handle cross execution for example.
    """
    options = thistest.options
    harness_args = []
    if options:
        if options.target:
            harness_args.extend(
                [
                    sys.executable,
                    which("run-cross2"),
                    "--save-temps",
                ]
            )
            harness_args.append(f"--target={options.target}")

    harness_args.append(executable)
    harness_args.extend(args)

    thistest.log(f"Harness run command:{os.linesep}\t", False)
    return run_wrapper(harness_args, output_in_baseline, allow_failure, **run_args)


def run_tgen_marshalling_test(
    test_prj: str,
    test_prj_src: list[str],
    test_prj_objdir: str = "obj",
    check_prj: str | None = None,
):
    """
    Run a "classic" tgen_marshalling based test, where the tgen_marshalling
    program is invoked on test_prj, for the sources listed in test_prj_src,
    then check_prj is compiled and the programs produced in `exe_check` are
    executed. The later should not produce any output in case everything is ok
    with marshalling, as this first step is never executed on cross configs.
    gnattest is then invoked to generate test on test_prj, the harness is built
    and executed.

    If check_prj is empty, only tgen_support is compiled as a sanity check.
    """
    # First the tgen_marshalling part, if not on cross configs
    if not thistest.env.is_cross:
        templates_path = os.path.join(
            os.path.dirname(os.path.dirname(which("gnattest"))),
            "share",
            "tgen",
            "templates",
        )
        os.makedirs(test_prj_objdir, exist_ok=True)
        run_command(
            "tgen_marshalling",
            test_prj,
            [
                f"--templates-dir={templates_path}",
                "-o",
                f"{test_prj_objdir}/tgen_support",
            ]
            + test_prj_src,
        )
        # If we were not provided with an actual verification project, just
        # compile tgen_support as a sanity check
        actual_check_prj = check_prj
        if not actual_check_prj:
            actual_check_prj = os.path.join(
                test_prj_objdir, "tgen_support", "tgen_support"
            )
        run_command("gprbuild", actual_check_prj, ["-q"])
        if os.path.exists("exe_check"):
            for exec in glob("exe_check/*"):
                run_wrapper([exec])

    run_gnattest(test_prj, ["-q", "--gen-test-vectors"])
    build_harness(f"{test_prj_objdir}/gnattest/harness/test_driver.gpr", ["-q"])
    run_harness(f"{test_prj_objdir}/gnattest/harness/test_runner")
