#!/usr/bin/env python

import glob
import json
import os
from pathlib import Path
from suite.cutils import remove_file
from suite.tutils import build_harness, run_command, run_gnattest, run_harness
from suite.context import thistest

# Create and build gnattest harness.
ret_gnattest = run_gnattest("simple.gpr", ["--gen-test-vectors", "-dn"])
ret_gprbuild = build_harness("obj/gnattest/harness/test_driver.gpr", ["-q"])

json_path = Path("obj/gnattest/tests/JSON_Tests/simple_tgen_dup.json")

# Remove the TGen generated json test case list.
remove_file(json_path)

base_dirir = os.getenv("TMPDIR", "obj")
tgen_generation_file = f"{base_dirir}/GNAT-*/tgen_Harness/simple_tgen_dup-tgen_generation.adb"

# Find the TGen generator directory.
match_file = glob.glob(tgen_generation_file)

if len(match_file) == 0:
    print(f"Nothing was matched when using the base {tgen_generation_file}")
    thistest.n_failed += 1
    thistest.result()

tgen_generation_file = match_file[0]
tgen_generation_gpr = Path(match_file[0]).parent / "tgen_generation_harness.gpr"
tgen_generation_bin = Path(match_file[0]).parent / "obj" / "generation_main"

# Get the content of the TGen generator source file.
with open(tgen_generation_file, "r") as f:
    content = f.read()

# Replace the random generator by a fixed value.
left_value = r'Values.Get("param_values").Get("Left")'
right_value = r'Values.Get("param_values").Get("Right")'
new_value = "TGen.JSON.Create (4)"
content = content.replace(left_value, new_value)
content = content.replace(right_value, new_value)

# Write back the updated file content.
with open(tgen_generation_file, "w") as f:
    f.write(content)

# Build the modified TGen generator.
run_command("gprbuild", str(tgen_generation_gpr), output_in_baseline=False)

# Run the modified TGen generator.
run_harness(str(tgen_generation_bin))

# Read the content of the TGen generated json test case list.
with open(json_path, "r") as j:
    data = json.load(j)

values = data.values()
# Check there is only one object inside.
if len(values) == 1:
    elem = list(values)[0]
    if "test_vectors" in elem:
        vectors_len = len(elem["test_vectors"])
        # Check there is only 1 element in the test_vectors and not 5.
        # By default, tgen generates 5 test cases and in this test it would be
        # 5 times the same test.
        if vectors_len != 1:
            print(f"Too many test cases generated by TGen: got {vectors_len} expected 1.")
            thistest.n_failed += 1
    else:
        print(f"test_vectors field not found in {json_path}")
        thistest.n_failed += 1
else:
    print(f"There should be only 1 value in {json_path}, got {len(values)}")
    thistest.n_failed += 1

ret_run = run_harness("obj/gnattest/harness/test_runner")

thistest.result()
