from glob import glob

from re import Match

import os
from pathlib import Path

from typing import AnyStr

from e3.testsuite.driver.classic import TestAbortWithError, TestSkip
from e3.testsuite.driver.diff import PatternSubstitute
from e3.fs import cp

from drivers.base_driver import BaseDriver


class Address_Hider(PatternSubstitute):
    """
    Refiner that identifies addresses from a symbolic Ada traceback and hides
    the addresses, to stabilize the output. All consecutive addresses separated
    by a space will be collapsed into a single placeholder as the length of a
    traceback may vary due to factors outside of gnattest/tgen's control.
    """

    def __init__(self):
        super().__init__(
            pattern=r"(0x[0-9a-f]{6,} ?)+",
            replacement="<addr_or_backtrace>",
        )


def build_lineno_replacement(m : Match) -> str:
    """
    Assuming the match instance contains a nested match group containing
    a filename, return filename:<line_number> to be used as baseline placeholder
    """
    return m.group(1) + ":<line_number>"


class LineHider(PatternSubstitute):
    """
    Refiner that identifies the line of a test procedure in a gnattest harness
    output and replaces it by a placeholder. The line at which test procedure
    is generated in the harness has no relevance, and can vary depending on the
    target.
    """

    def __init__(self):
        super().__init__(
            pattern=r" \((.*-test_data-test_.*[0-9a-f]*.adb):[0-9]*\)",
            replacement=build_lineno_replacement,
        )


class GNATTestTgenDriver(BaseDriver):
    """
    Test driver to execute gnattest in test generation mode (with TGen)
    The driver will attempt to run "gnattest --gen-test-vectors
    --dump-test-inputs -P<proj>" on the first .gpr file found on the test
    directory, and log the output, then build and run the generated test
    harness. The test harness execution log is also recorded in the output.
    """

    @property
    def baseline_file(self):
        """
        Only override the baseline filename when in gnatfuzz test mode
        """
        if os.environ.get("GNATTEST_GNATFUZZ", None):
            return "gnattest_baseline.out", False
        else:
            return super().baseline_file

    @property
    def tool_dirname(self):
        return "test"

    @property
    def output_refiners(self):
        return super().output_refiners + [Address_Hider(), LineHider()]

    def set_up(self):
        super().set_up()

        # gnattest_tgen should not be run in cross configs for now
        if self.env.main_options and self.env.main_options.target:
            raise TestSkip("TGen does not run for cross targets yet")

    def run(self):
        # generate a default gpr file if the test asks for one
        if self.test_env.get("default-gpr", False):
            gpr_file = os.path.join(self.working_dir(), "user_project.gpr")
            cp(
                os.path.join(
                    self.shared_dir(),
                    "gnatfuzz_default_resources",
                    "user_project.gpr",
                ),
                gpr_file,
            )

        # Try to locate one in the test dir otherwise
        else:
            gpr_file = glob(os.path.join(self.working_dir(), "*.gpr"), recursive=False)
            if len(gpr_file) == 0:
                raise TestAbortWithError(
                    "Could not find gpr project file on which to run gnattest:"
                    f" {gpr_file} (cwd: {self.working_dir()})"
                )

            gpr_file = gpr_file[0]

        gnattest_args = [
            "gnattest",
            f"-P{gpr_file}",
            "--gen-test-vectors",
            "-gnat2022",
        ]

        # Suppress test input dumping if specified in the test.yaml file
        if not self.test_env.get("suppress_test_dump", False):
            gnattest_args.append("--dump-test-inputs")

        # Generate TGen wrappers for gnatfuzz internal testsuite. GNATfuzz benchmarks
        # and demos being end-to-end tests, we can assume that they will always run at
        # least the analyze and generate phase.
        # It is also possible that the test is meant to run using the fuzz-everything
        # workflow, in this case the test name is prefixed with a "eag".
        if self.test_name.startswith("ag") or self.test_name.startswith("eag"):
            gnattest_args.append("--gen-wrappers")

        if os.environ.get("GNATTEST_DEBUG", None):
            # Enable debug log and preserve generation harness
            gnattest_args.extend(["-d1", "-dn"])
        else:
            # Silence execution
            gnattest_args.append("-q")

        # Append extra arguments specified in the test.yaml file
        gnattest_args += self.test_env.get("extra_gnattest_args", [])

        # Generate a test harness with tests generated by TGen
        self.shell(gnattest_args)

        # Get the object directory to be able to build the harness. This assumes
        # there is no Harness_Dir attribute in the project file.
        harness_dir = self.test_env.get(
            "harness_dir",
            os.path.join(self.working_dir(), "obj", "gnattest", "harness"),
        )
        harness_dir = ""
        for path in Path(self.working_dir()).rglob('harness'):
            harness_dir = path

        td_prj = os.path.join(harness_dir, "test_driver.gpr")
        support_lib_prj = os.path.join(harness_dir, "tgen_support", "tgen_support.gpr")
        if not os.path.exists(td_prj):
            raise TestAbortWithError("Could not locate test harness project")

        gprbuild_args = ["gprbuild", f"-P{td_prj}", "-q"]

        # Determine if the test harness needs to be compiled for test dumping mode
        has_test_dump = "--dump-test-inputs" in gnattest_args
        if has_test_dump:
            gprbuild_args += [
                "--src-subdirs=gnattest-instr",
                f"--implicit-with={support_lib_prj}",
            ]

        # Append extra gpbuild args if specified in the test.yaml file
        gprbuild_args += self.test_env.get("extra_gprbuild_args", [])

        self.shell(gprbuild_args)

        if self.test_env.get("suppress_test_runner_execution", False):
            return

        # Finally, run the test harness. Do not register failure exit codes as
        # it is likely that some tests may crash the subprogram under test.
        td_runner = os.path.join(os.path.dirname(td_prj), "test_runner")
        self.shell(
            [td_runner] + self.test_env.get("extra_run_args", []), catch_error=False
        )

        # Log the number of test files that were created by the test runner, if
        # test input dumping was enabled.
        if has_test_dump:
            num_tests = len(
                glob(os.path.join(self.working_dir(), "tgen_test_inputs", "*"))
            )
            self.output.log += f"Test runner dumped {num_tests} tests\n"
